create api-schema by openapi-gen #10
hoka-isdl/MERS pull request #13
Opened 2023-03-21 02:54 UTC by hoka-isdl

reactプロジェクトのAPIスキーマを生成しました．
ご確認お願いします．

実行コマンド
- npm install -g @openapitools/openapi-generator-cli
- npm run generate-typescript-axios

関連Issue
- #10

2023-03-21 11:26 UTC, Be3751 commented
@hoka-isdl PRありがとう〜ひとまずtypescript-axiosのスキーマがちゃんと生成されていて良いと思う。
次の段階の作業として、以下2点を行った上で改めてスキーマ生成してほしい！
- tagsを追記
  - 参考箇所：[API 定義時の注意点その1 tag は必須](https://zenn.dev/offers/articles/20220620-openapi-generator#api-%E5%AE%9A%E7%BE%A9%E6%99%82%E3%81%AE%E6%B3%A8%E6%84%8F%E7%82%B9%E3%81%9D%E3%81%AE1-tag-%E3%81%AF%E5%BF%85%E9%A0%88)
- OperationIdを追記
  - 参考箇所：[API 定義時の注意点その2 OperationId も必須且つ行儀よく命名](https://zenn.dev/offers/articles/20220620-openapi-generator#api-%E5%AE%9A%E7%BE%A9%E6%99%82%E3%81%AE%E6%B3%A8%E6%84%8F%E7%82%B9%E3%81%9D%E3%81%AE2-operationid-%E3%82%82%E5%BF%85%E9%A0%88%E4%B8%94%E3%81%A4%E8%A1%8C%E5%84%80%E3%82%88%E3%81%8F%E5%91%BD%E5%90%8D)

2023-03-21 11:27 UTC, Be3751 requested changes
@hoka-isdl PRありがとう〜ひとまずtypescript-axiosのスキーマがちゃんと生成されていて良いと思う。次の段階の作業として、以下2点を行った上で改めてスキーマ生成してほしい！
- tagsを追記
  - 参考箇所：[API 定義時の注意点その1 tag は必須](https://zenn.dev/offers/articles/20220620-openapi-generator#api-%E5%AE%9A%E7%BE%A9%E6%99%82%E3%81%AE%E6%B3%A8%E6%84%8F%E7%82%B9%E3%81%9D%E3%81%AE1-tag-%E3%81%AF%E5%BF%85%E9%A0%88)
- OperationIdを追記
  - 参考箇所：[API 定義時の注意点その2 OperationId も必須且つ行儀よく命名](https://zenn.dev/offers/articles/20220620-openapi-generator#api-%E5%AE%9A%E7%BE%A9%E6%99%82%E3%81%AE%E6%B3%A8%E6%84%8F%E7%82%B9%E3%81%9D%E3%81%AE2-operationid-%E3%82%82%E5%BF%85%E9%A0%88%E4%B8%94%E3%81%A4%E8%A1%8C%E5%84%80%E3%82%88%E3%81%8F%E5%91%BD%E5%90%8D)

2023-03-25 04:14 UTC, hoka-isdl commented
@Be3751 
tagsおよびoperationIdの追記に関しまして，完了いたしました．
API定義ファイルを変更したのでもしかするとbackendで自動生成したファイルは再度生成する必要がある可能性があると思いました．
ご確認よろしくお願いいたします．

関連Issue
- #10

2023-03-26 13:37 UTC, Be3751 commented
@hoka-isdl 
ありがとう！追加作業が出る前かoperationIdとtagsの記述はできてたから、openapi.yamlを編集したのではなくapi.tsを直接編集した感じ？
新しいコミットには、api.tsの差分しかなくて...。

2023-03-26 14:11 UTC, hoka-isdl commented
すみません．openapi.yamlの変更が含まれてませんでした．
申し訳ございません．
backend側の自動生成に関して，承知いたしました．
openapi.yamlとともにコミットさせていただきます．
自動生成した際のコマンドは教えていただくことは可能でしょうか．

2023-03-26 14:26 UTC, Be3751 commented
@hoka-isdl 
お願いします！ごめん、そういや共有せずにしれっとREADMEだけ更新してました。
[READMEのこの箇所](https://github.com/hoka-isdl/MERS#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%81%97%E3%81%9Fopenapi-generator%E3%81%AB%E3%82%88%E3%82%8B%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%9E%E3%81%AE%E7%94%9F%E6%88%90)を参考にしてみてほしい。

2023-03-30 02:10 UTC, merged